packages:
  base: !include base.yaml
  addon_bluetooth_proxy: !include addons/bluetooth-proxy.yaml

substitutions:
  bluetooth_proxy_active_connections: "false"

external_components:
  - source: github://tjhorner/esphome-custom-components
    components: [ project_version ]

text_sensor:
  - platform: project_version
    name: "Upsy Desky Firmware Version"
    internal: true

logger:
  level: INFO

wifi:
  ap:
    password: "hunter2hunter2"

captive_portal:

improv_serial:

esp32_improv:
  authorizer: false

api:
  reboot_timeout: 0s

web_server:
  port: 80
  js_url: "https://upsy-desky.tjhorner.dev/esphome-webserver/www.js"

ota:
  password: ""

dashboard_import:
  package_import_url: github://tjhorner/upsy-desky/firmware/stock.yaml@v2.0.0
